#pragma once

int FANCY_FONT;
char* FONT_DPIPE_TOP_LEFT;
char* FONT_DPIPE_TOP_RIGHT;
char* FONT_DPIPE_BOTTOM_LEFT;
char* FONT_DPIPE_BOTTOM_RIGHT;
char* FONT_DPIPE_VERT_BAR;
char* FONT_DPIPE_HORI_BAR;
char* FONT_DPIPE_TBAR_RIGHT;
char* FONT_DPIPE_TBAR_LEFT;
char* FONT_DPIPE_TBAR_UP;
char* FONT_DPIPE_TBAR_DOWN;
char* FONT_DPIPE_CROSSING;
char* FONT_COIN_PLAYER1;
char* FONT_COIN_PLAYER2;
char* FONT_COIN_EMPTY;

void setFancy(int fancyActivated)
{
	if (fancyActivated){
		FONT_DPIPE_TOP_LEFT = "╔";
		FONT_DPIPE_TOP_RIGHT = "╗";
		FONT_DPIPE_BOTTOM_LEFT = "╚";
		FONT_DPIPE_BOTTOM_RIGHT = "╝";
		FONT_DPIPE_VERT_BAR = "║";
		FONT_DPIPE_HORI_BAR = "═";
		FONT_DPIPE_TBAR_RIGHT = "╠";
		FONT_DPIPE_TBAR_LEFT = "╣";
		FONT_DPIPE_TBAR_UP = "╩";
		FONT_DPIPE_TBAR_DOWN = "╦";
		FONT_DPIPE_CROSSING = "╬";
	} else {
		FONT_DPIPE_TOP_LEFT = "/";
		FONT_DPIPE_TOP_RIGHT = "\\";
		FONT_DPIPE_BOTTOM_LEFT = "\\";
		FONT_DPIPE_BOTTOM_RIGHT = "/";
		FONT_DPIPE_VERT_BAR = "|";
		FONT_DPIPE_HORI_BAR = "-";
		FONT_DPIPE_TBAR_RIGHT = "(";
		FONT_DPIPE_TBAR_LEFT = ")";
		FONT_DPIPE_TBAR_UP = "v";
		FONT_DPIPE_TBAR_DOWN = "^";
		FONT_DPIPE_CROSSING = "+";
	}
	FONT_COIN_PLAYER1 = "X";
	FONT_COIN_PLAYER2 = "O";
	FONT_COIN_EMPTY = " ";

}
